# Generated by Django 2.1.7 on 2019-03-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('k_categoria', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('n_nombre', models.CharField(max_length=50)),
                ('n_descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('k_identificaciont', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('k_tipoidt', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('k_identificacion', models.DecimalField(decimal_places=65535, max_digits=65535, primary_key=True, serialize=False)),
                ('k_tipoid', models.CharField(max_length=2)),
                ('n_nombre', models.CharField(max_length=50)),
                ('n_apellido', models.CharField(max_length=50)),
                ('o_email', models.CharField(max_length=50)),
                ('o_celular', models.CharField(max_length=50)),
                ('o_telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('o_direccion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('k_detalle', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('q_cantidad', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('v_subtotal', models.DecimalField(decimal_places=65535, max_digits=65535)),
            ],
            options={
                'db_table': 'detalle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('k_orden', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('f_orden', models.DateField()),
                ('k_tipoid', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'orden',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('k_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('n_nombre', models.CharField(max_length=50)),
                ('n_descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('v_precio', models.DecimalField(decimal_places=65535, max_digits=65535)),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tendero',
            fields=[
                ('k_identificacion', models.DecimalField(decimal_places=65535, max_digits=65535, primary_key=True, serialize=False)),
                ('k_tipoid', models.CharField(max_length=2)),
                ('n_nombre', models.CharField(max_length=50)),
                ('n_apellido', models.CharField(max_length=50)),
                ('o_email', models.CharField(max_length=50)),
                ('o_celular', models.CharField(max_length=50)),
                ('o_telefono', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tendero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('k_identificaciont', models.DecimalField(decimal_places=65535, max_digits=65535, primary_key=True, serialize=False)),
                ('k_tipoidt', models.CharField(max_length=2)),
                ('n_nombre', models.CharField(max_length=50)),
                ('o_direccion', models.CharField(max_length=100)),
                ('k_identificacion', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('k_tipoid', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'tienda',
                'managed': False,
            },
        ),
    ]
