# Generated by Django 2.1.7 on 2019-03-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendero', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('k_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('n_nombre', models.CharField(max_length=50)),
                ('n_descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('v_precio', models.DecimalField(decimal_places=65535, max_digits=65535)),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
    ]
